version: "3"

tasks:
  format:
    desc: Format and auto-fix code
    aliases: [fmt]
    cmds:
      - golangci-lint run --fix ./...

  lint:
    desc: Run linters (no fixes)
    cmds:
      - golangci-lint run ./...

  test:
    desc: Run tests
    cmds:
      - go test ./...
